language: node_js
node_js:
  - node
  
script:
  - npm run test
  - npm run test:coveralls
  - npm run test:linter

notifications:
  email: false

addons:
  artifacts:
    paths:
      - ./coverage/lcov-report
    target_paths: $TRAVIS_BUILD_NUMBER